services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgresql
    env_file: 
      - .env
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
  oss:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    env_file:
      - .env
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - oss:/data
    command: server --console-address ":9001" /data
    restart: on-failure
volumes:
  db:
  oss: