"""empty message

Revision ID: 8f2f96f6311b
Revises: bd7891873488
Create Date: 2025-09-28 16:44:40.711873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f2f96f6311b'
down_revision: Union[str, Sequence[str], None] = 'bd7891873488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.drop_index(op.f('ix_m2m_world_character_character_id'), table_name='m2m_world_character')
    op.drop_index(op.f('ix_m2m_world_character_world_id'), table_name='m2m_world_character')
    op.drop_table('m2m_world_character')
    op.execute('INSERT INTO "user" (email, nickname, password, gender, avatar, disabled, language, is_admin, is_delete, created_at, updated_at)\n    VALUES (\'zoulee24@qq.com\', \'loreuser\', \'123456\', \'男\', \'/lorelm/resource/default_avatar.webp\', false, \'简体中文\', true, false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)\n    ON CONFLICT DO NOTHING;')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m2m_world_character',
    sa.Column('world_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name=op.f('m2m_world_character_character_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['world.id'], name=op.f('m2m_world_character_world_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('m2m_world_character_pkey')),
    comment='世界角色关联表'
    )
    op.create_index(op.f('ix_m2m_world_character_world_id'), 'm2m_world_character', ['world_id'], unique=False)
    op.create_index(op.f('ix_m2m_world_character_character_id'), 'm2m_world_character', ['character_id'], unique=False)
    # ### end Alembic commands ###
