/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatHistory: typeof import('./../components/ChatHistory.vue')['default']
    ChatInput: typeof import('./../components/ChatInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    MagicCard: typeof import('./../components/MagicCard.vue')['default']
    Markdown: typeof import('./../components/MarkdownRender/src/plugins/markdown.ts')['default']
    MarkdownRender: typeof import('./../components/MarkdownRender/index.ts')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./../components/MarkdownRender/src/index.vue')['default']
  }
}
